"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path
from urllib.parse import parse_qs, unquote, urlparse

from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / ".env")


def _env_bool(name, default="False"):
    return os.environ.get(name, default).strip().lower() in ("1", "true", "yes", "on")


def _env_list(name, default=""):
    return [item.strip() for item in os.environ.get(name, default).split(",") if item.strip()]


def _env_first(*names, default=""):
    for name in names:
        value = os.environ.get(name)
        if value is not None and value != "":
            return value
    return default


def _env_bool_first(*names, default="False"):
    for name in names:
        if name in os.environ:
            return _env_bool(name)
    return _env_bool("__unused__", default)


def _is_postgres_pooler(host, port):
    host = (host or "").lower()
    return "-pooler" in host or str(port) == "6543"


def _postgres_runtime_options(host="", port="5432"):
    """Neon pooled URLs go through PgBouncer (transaction mode)."""
    disable_cursors = _env_bool(
        "DB_DISABLE_SERVER_SIDE_CURSORS",
        default="True" if _is_postgres_pooler(host, port) else "False",
    )
    return {
        "CONN_MAX_AGE": int(os.environ.get("DB_CONN_MAX_AGE", "0")),
        "CONN_HEALTH_CHECKS": True,
        "DISABLE_SERVER_SIDE_CURSORS": disable_cursors,
    }


def _database_from_url(url):
    parsed = urlparse(url)
    if parsed.scheme not in ("postgres", "postgresql"):
        raise ImproperlyConfigured("DATABASE_URL must be a postgresql:// or postgres:// URL.")

    query = parse_qs(parsed.query)
    sslmode = (query.get("sslmode") or [os.environ.get("DB_SSLMODE", "require")])[0]
    options = {"sslmode": sslmode}
    if query.get("channel_binding"):
        options["channel_binding"] = query["channel_binding"][0]

    host = parsed.hostname or ""
    port = str(parsed.port or 5432)
    config = {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": unquote(parsed.path.lstrip("/")),
        "USER": unquote(parsed.username or ""),
        "PASSWORD": unquote(parsed.password or ""),
        "HOST": host,
        "PORT": port,
        "OPTIONS": options,
    }
    config.update(_postgres_runtime_options(host, port))
    return config


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# Cloud Run sets K_SERVICE. Production default is DEBUG=False even if DEBUG is omitted.
IS_CLOUD_RUN = bool(os.environ.get("K_SERVICE"))
IS_BUILD = _env_bool("DJANGO_BUILD")

# Local `runserver` without .env stays DEBUG=True. Cloud Run / production defaults to False.
# Accept both DEBUG and DJANGO_DEBUG.
DEBUG = _env_bool_first(
    "DEBUG",
    "DJANGO_DEBUG",
    default="False" if IS_CLOUD_RUN else "True",
)

# Accept both SECRET_KEY and DJANGO_SECRET_KEY. Never ship a production default.
SECRET_KEY = _env_first("SECRET_KEY", "DJANGO_SECRET_KEY")
if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = "django-insecure-local-dev-only-do-not-use-in-production"
    else:
        raise ImproperlyConfigured(
            "SECRET_KEY or DJANGO_SECRET_KEY must be set when DEBUG is False."
        )

ALLOWED_HOSTS = _env_list("ALLOWED_HOSTS") or _env_list(
    "DJANGO_ALLOWED_HOSTS",
    "localhost,127.0.0.1",
)

# Cloud Run health checks use *.run.app Host headers.
if IS_CLOUD_RUN and ".run.app" not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append(".run.app")

CSRF_TRUSTED_ORIGINS = _env_list("CSRF_TRUSTED_ORIGINS")

# Cloud Run (and other proxies) terminate HTTPS and forward HTTP to Gunicorn.
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
USE_X_FORWARDED_HOST = True

if not DEBUG:
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    "rest_framework_simplejwt.token_blacklist",
    "drf_spectacular",
    "corsheaders",
    'users',
    'common',
    'trips',
    'schedules',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "common.middleware.RequestIdMiddleware",
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases
#
# Priority:
#   1. DATABASE_URL (Neon / Cloud Run)
#   2. DB_HOST + DB_NAME / DB_USER / DB_PASSWORD / DB_PORT
#   3. SQLite — local development only (DEBUG=True)

database_url = (os.environ.get("DATABASE_URL") or "").strip()
if database_url:
    DATABASES = {"default": _database_from_url(database_url)}
elif os.environ.get("DB_HOST"):
    db_host = os.environ.get("DB_HOST")
    db_port = os.environ.get("DB_PORT", "5432")
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.environ.get("DB_NAME", "triptailor"),
            "USER": os.environ.get("DB_USER", ""),
            "PASSWORD": os.environ.get("DB_PASSWORD", ""),
            "HOST": db_host,
            "PORT": db_port,
            "OPTIONS": {
                "sslmode": os.environ.get("DB_SSLMODE", "prefer"),
            },
        }
    }
    DATABASES["default"].update(_postgres_runtime_options(db_host, db_port))
else:
    if not DEBUG and not IS_BUILD:
        raise ImproperlyConfigured(
            "DATABASE_URL or DB_HOST must be set when DEBUG is False."
        )
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'ko'

TIME_ZONE = 'Asia/Seoul'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/
# WhiteNoise serves admin / spectacular assets from STATIC_ROOT on Cloud Run.

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / "staticfiles"

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
    },
}


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}

#login
AUTH_USER_MODEL = "users.User"

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),

    "EXCEPTION_HANDLER": "common.exceptions.custom_exception_handler",
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}

SPECTACULAR_SETTINGS = {
    "TITLE": "TripTailor API",
    "DESCRIPTION": "TripTailor 백엔드 API 문서",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    "SWAGGER_UI_SETTINGS": {
        "persistAuthorization": True,
    },
}

SIMPLE_JWT = {
    "USER_ID_FIELD": "user_id",
    "USER_ID_CLAIM": "user_id",
}

FRONTEND_BASE_URL = os.environ.get("FRONTEND_BASE_URL", "http://localhost:3000")

# Optional regex list, e.g. https://.*\\.vercel\\.app
CORS_ALLOWED_ORIGIN_REGEXES = _env_list("CORS_ALLOWED_ORIGIN_REGEXES")

#TourAPI 관련 설정
TOUR_API_SERVICE_KEY = os.environ.get("TOUR_API_SERVICE_KEY")
TOUR_API_BASE_URL = "https://apis.data.go.kr/B551011/KorService2"
