# Generated by Django 6.1 on 2026-08-14 03:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('trip_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('participant_limit', models.PositiveIntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('invite_code', models.CharField(max_length=50, unique=True)),
                ('invite_url', models.URLField(max_length=500)),
                ('status', models.CharField(choices=[('COLLECTING_RESPONSES', '응답 수집 중'), ('PLANNING', '일정 생성 중'), ('READY', '일정 생성 완료')], default='COLLECTING_RESPONSES', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to=settings.AUTH_USER_MODEL)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='trips.region')),
            ],
            options={
                'db_table': 'trips',
            },
        ),
    ]
