# Generated by Django 6.1 on 2026-08-14 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_trip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='area_code',
        ),
        migrations.AddField(
            model_name='region',
            name='l_dong_regn_code',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='region',
            name='l_dong_signgu_code',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='region',
            constraint=models.UniqueConstraint(fields=('l_dong_regn_code', 'l_dong_signgu_code'), name='unique_region_code'),
        ),
    ]
