# Generated by Django 6.1 on 2026-08-14 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0005_participant'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='invite_active',
            field=models.BooleanField(default=True),
        ),
    ]
