# Generated by Django 6.1 on 2026-08-16 11:05

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


def set_owner_roles(apps, schema_editor):
    Participant = apps.get_model("trips", "Participant")
    Participant.objects.filter(
        user_id=models.F("trip__owner_id"),
    ).update(role="LEADER")


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0006_trip_invite_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="participant",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="participant",
            name="role",
            field=models.CharField(
                choices=[("LEADER", "리더"), ("MEMBER", "멤버")],
                default="MEMBER",
                max_length=20,
            ),
        ),
        migrations.RunPython(set_owner_roles, migrations.RunPython.noop),
        migrations.CreateModel(
            name="ParticipantPreference",
            fields=[
                (
                    "preference_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "budget_band",
                    models.CharField(
                        choices=[
                            ("LOW", "낮음"),
                            ("MID", "중간"),
                            ("HIGH", "높음"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "accommodation_type",
                    models.CharField(
                        choices=[
                            ("HOTEL", "호텔"),
                            ("PENSION", "펜션"),
                            ("GUESTHOUSE", "게스트하우스"),
                            ("ETC", "기타"),
                        ],
                        max_length=30,
                    ),
                ),
                ("must_haves", models.TextField(blank=True, default="")),
                ("additional_notes", models.TextField(blank=True, null=True)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "participant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preference",
                        to="trips.participant",
                    ),
                ),
            ],
            options={
                "db_table": "participant_preferences",
            },
        ),
    ]
