# Generated by Django 6.1 on 2026-08-15 14:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("trips", "0006_trip_invite_active"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "schedule_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                ("place", models.CharField(blank=True, max_length=200, null=True)),
                ("date", models.DateField()),
                ("start_time", models.TimeField(blank=True, null=True)),
                ("end_time", models.TimeField(blank=True, null=True)),
                ("order_index", models.PositiveIntegerField(default=0)),
                (
                    "source_type",
                    models.CharField(
                        choices=[("AI", "AI 생성"), ("MANUAL", "직접 추가")],
                        default="MANUAL",
                        max_length=10,
                    ),
                ),
                ("is_fixed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_schedules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="trips.trip",
                    ),
                ),
            ],
            options={
                "db_table": "schedules",
                "ordering": ["date", "order_index", "start_time"],
            },
        ),
        migrations.AddIndex(
            model_name="schedule",
            index=models.Index(
                fields=["trip", "date", "order_index"],
                name="schedules_trip_id_date_ord_idx",
            ),
        ),
    ]
