# Generated by Django 6.1 on 2026-09-04 15:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0001_initial'),
        ('trips', '0007_participant_role_and_preference'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccommodationStay',
            fields=[
                ('stay_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('place_id', models.CharField(blank=True, max_length=100, null=True)),
                ('place_name', models.CharField(max_length=200)),
                ('check_in_date', models.DateField()),
                ('check_out_date', models.DateField()),
                ('price_per_night_per_person', models.PositiveIntegerField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('source_type', models.CharField(choices=[('AI', 'AI 생성'), ('MANUAL', '직접 추가')], default='MANUAL', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'accommodation_stays',
                'ordering': ['check_in_date'],
            },
        ),
        migrations.RenameIndex(
            model_name='schedule',
            new_name='schedules_trip_id_c24552_idx',
            old_name='schedules_trip_id_date_ord_idx',
        ),
        migrations.AddField(
            model_name='accommodationstay',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_accommodation_stays', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accommodationstay',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accommodation_stays', to='trips.trip'),
        ),
    ]
